# Generated by Django 5.1 on 2024-08-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
