# Generated by Django 5.1 on 2024-08-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_brand_alter_carmodel_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('HatchBack', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Jeep', 'Jeep')], default='Jeep', max_length=10),
            preserve_default=False,
        ),
    ]
