# Generated by Django 5.1 on 2024-08-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_salons', '0001_initial'),
        ('cars', '0004_carmodel_body_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='auto_salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auto_salons.autosalonmodel'),
            preserve_default=False,
        ),
    ]
