# Generated by Django 5.1 on 2024-08-29 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_salons', '0001_initial'),
        ('cars', '0005_alter_carmodel_options_carmodel_auto_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='auto_salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='auto_salons.autosalonmodel'),
        ),
    ]
