# Generated by Django 5.1 on 2024-08-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_carmodel_body_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='state',
            new_name='region',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('UAH', 'Uah')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine',
            field=models.CharField(choices=[('Gasoline', 'Gasoline'), ('Gas', 'Gas'), ('Diesel', 'Diesel'), ('Electricity', 'Electricity'), ('Hybrid', 'Hybrid')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(choices=[('mechanics', 'Mechanics'), ('automatic', 'Automatic'), ('tiptronic', 'Tiptronic'), ('robot', 'Robot'), ('variator', 'Variator'), ('DCT', 'Dct')], default=23, max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('HatchBack', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Jeep', 'Jeep'), ('Roadster', 'Roadster'), ('Convertible', 'Convertible'), ('Sport Car', 'Sport Car'), ('Crossover', 'Crossover'), ('Pickup', 'Pickup'), ('Minivan', 'Minivan'), ('Van', 'Van'), ('Limousine', 'Limousine')], max_length=21),
        ),
    ]
