# Generated by Django 5.1 on 2024-08-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_state_carmodel_region_carmodel_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
