# Generated by Django 5.1 on 2024-09-02 17:57

import django.db.models.deletion
from django.db import migrations, models

import core.services.file_services


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_carmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='photo',
        ),
        migrations.CreateModel(
            name='CarPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=core.services.file_services.FileService.upload_car_photo)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.carmodel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
