# Generated by Django 5.1 on 2024-09-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_carmodel_photo_carphotomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('id',)},
        ),
    ]
