# Generated by Django 5.1 on 2024-09-02 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_carphotomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{1,24}$', ['First letter uppercase min 2 max 25 characters'])]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{1,24}$', 'First letter uppercase min 2 max 20 characters')]),
        ),
    ]
